name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Generate Artifacts
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.4

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build CLI
      env:
        BINARY_VERSION: "Release"
      run: |
        make build-ci

    - name: Build images
      run: |
        make docker-binary docker-build

    - name: Push commit specific images
      env:
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        echo ${PUSH_TOKEN} | \
          docker login -u ksyncrobot --password-stdin
        make docker-push

    - uses: actions/upload-artifact@v1
      with:
        name: bin
        path: bin

    - name: Create changelog
      uses: teaminkling/autologger@1.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_repository: ${{ github.repository }}

    - name: Upload assets to release
      uses: meeDamian/github-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: false
        files: >
          bin/ksync_darwin_amd64
          bin/ksync_linux_amd64
          bin/ksync_windows_amd64.exe
          bin/radar_darwin_amd64
          bin/radar_linux_amd64
          bin/radar_windows_amd64.exe
